# Assignment 2 Problem 2

In [ ]:
#############################################################################################################################



###############################################################################################################################

In [4]:
import numpy as np

In [14]:
DS1_train = np.genfromtxt('DS1_train.txt')
DS1_test = np.genfromtxt('DS1_test.txt')

In [15]:
#DS1_train = np.genfromtxt('F:\\Winter 2018\\Applied ML\\winter 2018\\Assignments\\assignment 2\\hwk2_datasets_corrected\\DS1_train.txt')
#DS1_test = np.genfromtxt('F:\\Winter 2018\\Applied ML\\winter 2018\\Assignments\\assignment 2\\hwk2_datasets_corrected\\DS1_test.txt')

In [16]:
print(DS1_train.shape)
print(DS1_test.shape)

(2800, 21)
(1200, 21)


In [17]:
t_train = DS1_train[:,-1]
t_train = np.reshape(t_train,(-1,1))

t_test = DS1_test[:,-1]
t_test = np.reshape(t_test,(-1,1))

In [18]:
#t.shape

In [19]:
X_train = DS1_train[:,0:-1]
#print(X_train.shape)

X_test = DS1_test[:,0:-1]
#print(X_train.shape)

###  This mu calculation works as N1 and N2 are same (both class has same number of examples)

In [20]:
t_train.sum()

1400.0

In [21]:
N1 = t_train.sum()
N2 = DS1_train.shape[0] - N1

In [22]:
mu1=np.dot(X_train.T,t_train)/N1
mu1

array([[2.11729676],
       [2.00178424],
       [2.09192348],
       [2.0401792 ],
       [2.01858462],
       [2.07848594],
       [2.00259273],
       [2.052124  ],
       [2.07384159],
       [1.97268597],
       [2.02769579],
       [2.02677404],
       [2.01220721],
       [2.09373266],
       [2.07537323],
       [2.04733347],
       [2.09773404],
       [2.05521578],
       [2.05555106],
       [2.04908871]])

In [23]:
mu2 = np.dot(X_train.T,(1-t_train))/N2
mu2

array([[1.35706765],
       [1.31237939],
       [1.31775342],
       [1.3108699 ],
       [1.34970912],
       [1.26975399],
       [1.30127652],
       [1.30632173],
       [1.31702198],
       [1.27345847],
       [1.37233019],
       [1.2814685 ],
       [1.26069126],
       [1.38204133],
       [1.32485818],
       [1.31165057],
       [1.32814545],
       [1.32186326],
       [1.32409548],
       [1.24102691]])

In [ ]:
# Pc1 = N1 / (N1+N2)

# N1 = no of positive targets
# N2 = no of negative targets

In [24]:
Pc1 = N1 / ( N1+N2 )
Pc2 = 1 - Pc1


In [25]:
# compute sigma

In [26]:
featureNo = X_train.shape[1]
print(featureNo)

20


In [27]:
#Xc1 = X data belong to class 1

In [28]:
Xc1 = X_train*np.repeat(t_train,featureNo,axis=1)
print(Xc1.shape)
Xc1 = Xc1[~(Xc1==0).all(1)]
print(Xc1.shape)

(2800, 20)
(1400, 20)


In [29]:
# similarly compute Xc2 = data

In [30]:
Xc2 = X_train*np.repeat((1-t_train),featureNo,axis=1)
print(Xc2.shape)
Xc2 = Xc2[~(Xc2==0).all(1)]
print(Xc2.shape)

(2800, 20)
(1400, 20)


In [31]:
# compute S

In [32]:
#A = ( Xc1 - np.repeat(mu1.T,N1,axis = 0) )
A = Xc1 - mu1.T
S1 = np.dot(A.T,A)
print(S1.shape)

(20, 20)


In [33]:
B = Xc2 - mu2.T
S2 = np.dot(B.T,B)
print(S2.shape)

(20, 20)


In [34]:
N = N1+N2
sigma = (N1/N)*S1 + (N2/N)*S2

m1 >> mu1 >> positive >> target 1 >> class 1  | |
m0 >> mu0 >> negative >> target 0 >> class 2

In [35]:
W1 = np.dot(np.linalg.inv(sigma),(mu1 - mu2))

In [36]:
W1.shape

(20, 1)

In [37]:
c = np.linalg.inv(sigma)

In [38]:
W0 = (-1/2)*np.dot (np.dot(mu1.T,c) , mu1) + (1/2)*np.dot (np.dot(mu2.T,c) , mu2) + np.log(Pc1/Pc2)
print(W0)
print(W0.shape)

[[-0.01970927]]
(1, 1)


In [39]:
def sigm(x):
    import numpy as np
    y = 1/(1+np.exp(-x))
    return y

In [40]:
W1.shape

(20, 1)

In [41]:
np.linalg.inv(sigma).shape

(20, 20)

In [42]:
Pcx = np.dot(X_test,W1) + W0 
print(Pcx)

[[-0.00844383]
 [ 0.00491548]
 [-0.0029593 ]
 ...
 [-0.0003185 ]
 [-0.00393463]
 [ 0.00168675]]


In [43]:
Pcx = sigm(Pcx)
Pcx

array([[0.49788905],
       [0.50122887],
       [0.49926018],
       ...,
       [0.49992038],
       [0.49901634],
       [0.50042169]])

In [44]:
Pcx[Pcx <= 0.5] = 0
Pcx[Pcx > 0.5] = 1

In [45]:
True_Positive = np.sum(t_test*Pcx)
True_Positive

573.0

In [46]:
False_Positive = (Pcx>t_test).sum()
False_Positive

18

In [47]:
False_Negative = (Pcx<t_test).sum()
False_Negative

27

In [48]:
# no of prediction negative = no of prediciton - no of positive prediction
                            # no of prediciton = Pcx.shape[0] 
                            # no of positive prediction = Pcx.sum()

# True Negative = no of prediction negative - False_Negative
True_Negative = (Pcx.shape[0] - Pcx.sum()) - False_Negative
True_Negative

582.0

# Results

In [49]:
accuracy = (True_Positive + True_Negative)/ t_test.shape[0]
accuracy 

0.9625

In [50]:
precision = True_Positive/(True_Positive+False_Positive)
precision

0.9695431472081218

In [51]:
recall = True_Positive/(True_Positive+True_Negative)
recall

0.4961038961038961

In [52]:
F_measure = 2*(precision*recall)/(precision+recall)
F_measure

0.6563573883161512

In [58]:
mu1

array([[2.11729676],
       [2.00178424],
       [2.09192348],
       [2.0401792 ],
       [2.01858462],
       [2.07848594],
       [2.00259273],
       [2.052124  ],
       [2.07384159],
       [1.97268597],
       [2.02769579],
       [2.02677404],
       [2.01220721],
       [2.09373266],
       [2.07537323],
       [2.04733347],
       [2.09773404],
       [2.05521578],
       [2.05555106],
       [2.04908871]])

In [59]:
mu2

array([[1.35706765],
       [1.31237939],
       [1.31775342],
       [1.3108699 ],
       [1.34970912],
       [1.26975399],
       [1.30127652],
       [1.30632173],
       [1.31702198],
       [1.27345847],
       [1.37233019],
       [1.2814685 ],
       [1.26069126],
       [1.38204133],
       [1.32485818],
       [1.31165057],
       [1.32814545],
       [1.32186326],
       [1.32409548],
       [1.24102691]])

In [54]:
W0

array([[-0.01970927]])

In [55]:
W1

array([[-0.01045202],
       [ 0.00610652],
       [ 0.00383399],
       [ 0.00231079],
       [ 0.00702171],
       [ 0.00328694],
       [-0.01215903],
       [ 0.01746164],
       [ 0.02107953],
       [-0.00661686],
       [ 0.00947292],
       [ 0.00874185],
       [-0.0112186 ],
       [-0.00944737],
       [ 0.00420932],
       [-0.00947503],
       [-0.0211413 ],
       [ 0.00490763],
       [ 0.00042474],
       [ 0.00361979]])

In [56]:
sigma

array([[11260.45401634,  7726.06001277,  8722.95337339,  7121.05019957,
         8133.11073052,  8707.60215888,  6548.0466061 ,  7605.27255659,
         6948.60031562,  7153.1474866 ,  5543.99166954,  7335.32991508,
         9778.45721839,  8353.50187009,  8515.65583757,  8339.35271053,
         8206.65340617,  8000.32960549,  7811.73552453,  8118.87129475],
       [ 7726.06001277,  9697.6968995 ,  7596.25406397,  6006.09661775,
         7633.51627203,  7862.89853143,  6035.41799236,  5469.09059351,
         5711.25393111,  6822.89544647,  4739.86408114,  6385.93222   ,
         7987.53364687,  7160.14520971,  7725.25446245,  7338.50763244,
         7980.5917322 ,  7132.82178138,  7504.63700912,  7317.13462973],
       [ 8722.95337339,  7596.25406397, 10462.72618478,  6751.49202273,
         8200.41653488,  9401.86887791,  6591.35041386,  6725.27703118,
         6927.12399285,  7018.76426881,  4654.02930814,  6546.48024454,
         8770.53078685,  7298.98131536,  8717.39610448,  8455.