# Assignment 2 problem 5.1

In [1]:
#############################################################################################################################



###############################################################################################################################

In [2]:
import numpy as np

In [3]:
#DS2_train = np.genfromtxt('F:\\Winter 2018\\Applied ML\\winter 2018\\Assignments\\assignment 2\\hwk2_datasets_corrected\\DS2_train.txt')
#DS2_test = np.genfromtxt('F:\\Winter 2018\\Applied ML\\winter 2018\\Assignments\\assignment 2\\hwk2_datasets_corrected\\DS2_test.txt')

In [4]:
DS2_train = np.genfromtxt('DS2_train.txt')
DS2_test = np.genfromtxt('DS2_test.txt')

In [5]:
print(DS2_train.shape)
print(DS2_test.shape)

(2800, 21)
(1200, 21)


In [6]:
t_train = DS2_train[:,-1]
t_train = np.reshape(t_train,(-1,1))

t_test = DS2_test[:,-1]
t_test = np.reshape(t_test,(-1,1))

In [7]:
#t.shape

In [8]:
X_train = DS2_train[:,0:-1]
#print(X_train.shape)

X_test = DS2_test[:,0:-1]
#print(X_train.shape)

###  This mu calculation works as N1 and N2 are same (both class has same number of examples)

In [9]:
t_train.sum()

1400.0

In [10]:
N1 = t_train.sum()
N2 = DS2_train.shape[0] - N1

In [11]:
mu1=np.dot(X_train.T,t_train)/N1
mu1

array([[1.10933176],
       [1.04337353],
       [1.08710064],
       [1.03513281],
       [1.0540895 ],
       [1.01931427],
       [1.02233875],
       [1.05943621],
       [1.04492486],
       [1.0095645 ],
       [1.07407652],
       [1.03634172],
       [1.07338496],
       [1.07065069],
       [1.06676536],
       [1.03717917],
       [1.12545816],
       [1.0195795 ],
       [1.00959656],
       [1.07928161]])

In [12]:
mu2 = np.dot(X_train.T,(1-t_train))/N2
mu2

array([[1.20637971],
       [1.24578597],
       [1.23909664],
       [1.29948946],
       [1.21352091],
       [1.23816039],
       [1.24382555],
       [1.19727223],
       [1.21312223],
       [1.28847044],
       [1.29330546],
       [1.28408775],
       [1.26635248],
       [1.21113559],
       [1.21150247],
       [1.23737768],
       [1.26350945],
       [1.20329051],
       [1.26980984],
       [1.21744158]])

In [13]:
# Pc1 = N1 / (N1+N2)

# N1 = no of positive targets
# N2 = no of negative targets

In [14]:
Pc1 = N1 / ( N1+N2 )
Pc2 = 1 - Pc1


In [15]:
# compute sigma

In [16]:
featureNo = X_train.shape[1]
print(featureNo)

20


In [17]:
#Xc1 = X data belong to class 1

In [18]:
Xc1 = X_train*np.repeat(t_train,featureNo,axis=1)
print(Xc1.shape)
Xc1 = Xc1[~(Xc1==0).all(1)]
print(Xc1.shape)

(2800, 20)
(1400, 20)


In [19]:
# similarly compute Xc2 = data

In [20]:
Xc2 = X_train*np.repeat((1-t_train),featureNo,axis=1)
print(Xc2.shape)
Xc2 = Xc2[~(Xc2==0).all(1)]
print(Xc2.shape)

(2800, 20)
(1400, 20)


In [21]:
# compute S

In [22]:
#A = ( Xc1 - np.repeat(mu1.T,N1,axis = 0) )
A = Xc1 - mu1.T
S1 = np.dot(A.T,A)
print(S1.shape)

(20, 20)


In [23]:
B = Xc2 - mu2.T
S2 = np.dot(B.T,B)
print(S2.shape)

(20, 20)


In [24]:
N = N1+N2
sigma = (N1/N)*S1 + (N2/N)*S2

In [25]:
W1 = np.dot(np.linalg.inv(sigma),(mu1 - mu2))

In [26]:
W1.shape

(20, 1)

In [27]:
c = np.linalg.inv(sigma)

In [28]:
W0 = (-1/2)*np.dot (np.dot(mu1.T,c) , mu1) + (1/2)*np.dot (np.dot(mu2.T,c) , mu2) + np.log(Pc1/Pc2)
print(W0)
print(W0.shape)

[[5.78328839e-05]]
(1, 1)


In [29]:
def sigm(x):
    import numpy as np
    y = 1/(1+np.exp(-x))
    return y

In [30]:
W1.shape

(20, 1)

In [31]:
np.linalg.inv(sigma).shape

(20, 20)

In [32]:
Pcx = np.dot(X_test,W1) + W0 
print(Pcx)

[[-2.70181507e-06]
 [-2.71679015e-05]
 [ 1.81004437e-04]
 ...
 [ 6.33933825e-05]
 [ 1.51753608e-05]
 [ 2.82064985e-06]]


In [33]:
Pcx = sigm(Pcx)
Pcx

array([[0.49999932],
       [0.49999321],
       [0.50004525],
       ...,
       [0.50001585],
       [0.50000379],
       [0.50000071]])

In [34]:
Pcx[Pcx <= 0.5] = 0
Pcx[Pcx > 0.5] = 1

In [35]:
True_Positive = np.sum(t_test*Pcx)
True_Positive

310.0

In [36]:
False_Positive = (Pcx>t_test).sum()
False_Positive

314

In [37]:
False_Negative = (Pcx<t_test).sum()
False_Negative

290

In [38]:
# no of prediction negative = no of prediciton - no of positive prediction
                            # no of prediciton = Pcx.shape[0] 
                            # no of positive prediction = Pcx.sum()

# True Negative = no of prediction negative - False_Negative
True_Negative = (Pcx.shape[0] - Pcx.sum()) - False_Negative
True_Negative

286.0

# Results

In [39]:
accuracy = (True_Positive + True_Negative)/ t_test.shape[0]
accuracy 

0.49666666666666665

In [40]:
precision = True_Positive/(True_Positive+False_Positive)
precision

0.4967948717948718

In [41]:
recall = True_Positive/(True_Positive+True_Negative)
recall

0.5201342281879194

In [42]:
F_measure = 2*(precision*recall)/(precision+recall)
F_measure

0.5081967213114754

In [43]:
mu1

array([[1.10933176],
       [1.04337353],
       [1.08710064],
       [1.03513281],
       [1.0540895 ],
       [1.01931427],
       [1.02233875],
       [1.05943621],
       [1.04492486],
       [1.0095645 ],
       [1.07407652],
       [1.03634172],
       [1.07338496],
       [1.07065069],
       [1.06676536],
       [1.03717917],
       [1.12545816],
       [1.0195795 ],
       [1.00959656],
       [1.07928161]])

In [44]:
mu2

array([[1.20637971],
       [1.24578597],
       [1.23909664],
       [1.29948946],
       [1.21352091],
       [1.23816039],
       [1.24382555],
       [1.19727223],
       [1.21312223],
       [1.28847044],
       [1.29330546],
       [1.28408775],
       [1.26635248],
       [1.21113559],
       [1.21150247],
       [1.23737768],
       [1.26350945],
       [1.20329051],
       [1.26980984],
       [1.21744158]])

In [45]:
W0

array([[5.78328839e-05]])

In [46]:
W1

array([[ 5.25100739e-05],
       [-9.26007998e-06],
       [ 3.18304450e-05],
       [-3.43503148e-05],
       [-3.84234125e-05],
       [-9.70487776e-06],
       [ 3.95067380e-05],
       [ 2.11408796e-05],
       [-8.45523628e-06],
       [-5.45845613e-05],
       [-5.01263099e-05],
       [-4.66807428e-05],
       [-2.18103052e-05],
       [-5.94580898e-06],
       [ 5.19091173e-05],
       [-3.28798430e-06],
       [ 2.55625127e-05],
       [-9.67633571e-06],
       [ 1.73328027e-05],
       [ 3.54779597e-06]])