# Assignment 2 Problem 1

You will use a synthetic data set for the classication task that you'll generate yourself.
Generate two classes with 20 features each. Each class is given by a multivariate Gaussian
distribution, with both classes sharing the same covariance matrix. You are provided
with the mean vectors (DS1-m0 for mean vector of negative class and DS1-m1 for mean
vector of positive class) and the covariance matrix (DS1-cov). Generate 2000 examples
for each class, and label the data to be positive if they came from the Gaussian with
mean m1 and negative if they came from the Gaussian with mean m0. Randomly pick
30% of each class (i.e., 600 data points per class) as a test set, and train the classiers
on the remaining 70%. data When you report performance results, it should be on the
left out 30%. Call this dataset at DS1, and submit it with your code.

In [1]:
import numpy as np

In [2]:
#DS1_m_0 = np.genfromtxt('F:\\Winter 2018\\Applied ML\\winter 2018\\Assignments\\assignment 2\\hwk2_datasets_corrected\\DS1_m_0.txt',delimiter=',')

DS1_m_0 = np.genfromtxt('DS1_m_0.txt',delimiter=',')
DS1_m_0 = DS1_m_0[~np.isnan(DS1_m_0)]
DS1_m_0

array([1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3,
       1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3])

In [3]:
DS1_m_1 = np.genfromtxt('DS1_m_1.txt',delimiter=',')
#DS1_m_1 = np.genfromtxt('F:\\Winter 2018\\Applied ML\\winter 2018\\Assignments\\assignment 2\\hwk2_datasets_corrected\\DS1_m_1.txt',delimiter=',')

DS1_m_1 = DS1_m_1[~np.isnan(DS1_m_1)]
DS1_m_1

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2.])

In [4]:
DS1_Cov = np.genfromtxt('DS1_Cov.txt',delimiter=',')
#DS1_Cov = np.genfromtxt('F:\\Winter 2018\\Applied ML\\winter 2018\\Assignments\\assignment 2\\hwk2_datasets_corrected\\DS1_Cov.txt',delimiter=',')

DS1_Cov = DS1_Cov[~np.isnan(DS1_Cov)]
DS1_Cov = np.reshape(DS1_Cov,(20,20))
DS1_Cov.shape

(20, 20)

In [5]:
exampleNo = 2000 # given
crtTrainData = 0.7 #create 70% as training data

# Creating the features using mean and covariance matrix using multivariate gaussian distribution

In [6]:
DS1_neg = np.random.multivariate_normal(DS1_m_0, DS1_Cov, exampleNo)

In [7]:
np.mean(DS1_neg,0)

array([1.3640884 , 1.32204984, 1.30980195, 1.30714623, 1.34555654,
       1.29026204, 1.32585617, 1.32267899, 1.3401498 , 1.29432672,
       1.36597901, 1.33091216, 1.28429989, 1.37586098, 1.30521907,
       1.32777821, 1.34907814, 1.34623388, 1.34494293, 1.24603353])

In [8]:
DS1_pos = np.random.multivariate_normal(DS1_m_1, DS1_Cov, exampleNo)

In [9]:
np.mean(DS1_pos,0)

array([2.09643479, 2.03009881, 2.07555198, 2.04315464, 2.07055682,
       2.07861879, 2.05315597, 2.05024457, 2.05678   , 2.02133978,
       2.05236926, 2.04962678, 2.0380532 , 2.08643674, 2.06902112,
       2.06790712, 2.07539876, 2.05156968, 2.08063117, 2.08338535])

In [10]:
DS1_pos.shape[0]

2000

# Add labels to the data

In [11]:
DS1_pos = np.append(DS1_pos,np.ones((exampleNo,1))*(1),1)

In [12]:
DS1_neg = np.append(DS1_neg,np.zeros((exampleNo,1)),1)

In [13]:
DS1_neg.shape 

(2000, 21)

In [16]:
No_train_example =  np.int(exampleNo*crtTrainData)
No_test_example =  np.int(exampleNo - No_train_example)

In [17]:
DS1_pos_train = DS1_pos[0:No_train_example]
DS1_pos_test = DS1_pos[No_train_example:]

DS1_neg_train = DS1_neg[0:No_train_example]
DS1_neg_test = DS1_neg[No_train_example:]

# Create "DS1" dataset

In [18]:
DS1_train = np.append(DS1_neg_train,DS1_pos_train,0)
print(DS1_train.shape)
DS1_test = np.append(DS1_neg_test,DS1_pos_test,0)
print(DS1_test.shape)

(2800, 21)
(1200, 21)


In [19]:
#DS1 = np.append(DS1_neg,DS1_pos,0)
#DS1.shape

# shuffling the positive and negative labeled data

In [20]:
np.random.shuffle(DS1_train)
np.random.shuffle(DS1_test)

# Saving the data at "DS1"

In [23]:


#np.savetxt('F:\\Winter 2018\\Applied ML\\winter 2018\\Assignments\\assignment 2\\hwk2_datasets_corrected\\DS1_train.txt', DS1_train)
np.savetxt('DS1_train.txt', DS1_train)

#np.savetxt('F:\\Winter 2018\\Applied ML\\winter 2018\\Assignments\\assignment 2\\hwk2_datasets_corrected\\DS1_test.txt', DS1_test)
np.savetxt('DS1_test.txt', DS1_test)

In [22]:
import numpy as np
np.genfromtxt('DS1_train.txt')

array([[-1.17339485, -1.48479064, -2.56037157, ..., -3.90534307,
        -0.57784179,  0.        ],
       [ 1.28797053,  2.77250485,  3.5722785 , ...,  3.19538546,
         4.02961224,  1.        ],
       [-0.40981745,  2.07415376, -0.15652654, ..., -1.01596934,
         0.28141885,  0.        ],
       ...,
       [ 4.17136713,  1.30002233,  1.13082867, ...,  1.91219036,
         2.24306348,  0.        ],
       [ 1.17017613,  1.70969264, -0.57592499, ...,  0.73173263,
         2.9264506 ,  1.        ],
       [ 4.58502894,  5.62195549,  5.00773778, ...,  4.64661687,
         5.18822418,  1.        ]])

In [ ]:
np.genfromtxt('DS1_test.txt')

In [ ]:
##############################################################################################################################